{
	'disable_trim' : False,
	'wide' : False,
	'keep_aspect_ratio' : False,
	'output_format' : u'png',
	'dont_normalize' : False,
	'dont_sharpen' : False,
	'dont_grayscale' : False,
	'right2left' : False,
	'colors' : 256,
	'no_sort' : False,
	'no_process' : False,
	'despeckle' : False,
	'landscape' : False,
}